name: Dependency review

on:
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dependency Review
      uses: actions/dependency-review-action@v3.0.6


